<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.1.0</Version>
    <Title>AutoImplement</Title>
    <Authors>XFEstudio</Authors>
    <Company>寰宇朽力网络科技有限公司</Company>
    <Copyright>寰宇朽力网络科技有限公司版权所有</Copyright>
    <Description>自动生成实现类</Description>
    <PackageProjectUrl>https://github.com/XFEstudio/XFEExtension.NetCore.AutoImplement.git</PackageProjectUrl>
    <PackageIcon>logoIcon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/XFEstudio/XFEExtension.NetCore.AutoImplement.git</RepositoryUrl>
    <PackageTags>XFE;impl;implement;auto</PackageTags>
    <PackageReleaseNotes>
      现在，可以通过在CreateImpl特性的传参中设置属性来实现自定义实现类的类名、命名空间及可访问性修饰符
      且现在的实现类默认使用`internal`和`partial`修饰符，可以更加方便的修改实现类中的内容
    </PackageReleaseNotes>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\logoIcon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\XFEExtension.NetCore.AutoImplement.Analyzer\bin\Release\netstandard2.0\XFEExtension.NetCore.AutoImplement.Analyzer.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

</Project>
